#include "fsm.h"
#include "main.h"

/***************定义区****************/
enum ROBOT_STATE_TYPE ROBOT_STATE;//当前状态
enum ROBOT_STATE_TYPE LAST_STATE;//记录机器人上一次状态，用来实现中断功能
enum ROBOT_STATE_TYPE BEFORE_STATE;//用来实现二重中断 
struct ROBOT_NOW_TYPE ROBOT_NOW;//机器人自身实时状态
struct state_control STATE_COUNT={0,0,1};//计数控制状态
enum CALIBRATION_TYPE ROBOT_CALIBRATION;//校准状态
enum ROBOT_VISION_TYPE ROBOT_VISION;//视觉开关
enum ROBOT_GRAB_TYPE ROBOT_GRAB;//抓取状态
enum ROBOT_PUT_TYPE ROBOT_PUT;//投放
enum ROBOT_TRACKING_TYPE ROBOT_TRACKING;//移动
enum ROBOT_TURNAROUND_TYPE ROBOT_TURNAROUND;//转身

//有限状态机
void fsm_init(void)
{
	ROBOT_STATE=CALIBRATION;
	ROBOT_GRAB=GRAB_STOP;
	ROBOT_TRACKING=TRACKING_STOP;
	ROBOT_PUT=PUT_STOP;
	ROBOT_TURNAROUND=TURNAROUND_STOP;
	ROBOT_VISION=VISION_STOP;
	ROBOT_CALIBRATION=CALIBRATION_STOP;
}


//参考师兄的状态机代码，进行了改动
//实现了路径跟踪与非路径跟踪的融合,并可以设置中断进入状态模式(进入该模式下的中断形态)
//判断是否完成上一状态的任务并切换状态
//以逻辑顺序列出该状态该做的事
void FSM_WORK(void)//起到切换状态的作用
{
	switch(ROBOT_STATE)
  {
		//待机模式（当回到起始区时进入待机模式）
		case STANDBY:
		{
			ROBOT_GRAB=GRAB_STOP;
      ROBOT_TRACKING=TRACKING_STOP;
	    ROBOT_PUT=PUT_STOP;
	    ROBOT_VISION=VISION_STOP;
			ROBOT_CALIBRATION=CALIBRATION_STOP;
			ROBOT_TURNAROUND=TURNAROUND_STOP;
		}
		break;
		//校准模式(自编中断触发)
		case CALIBRATION:
		{
			if(STATE_COUNT.CALIBRATION_count==1)//第一次校准
			{
				ROBOT_GRAB=GRAB_STOP;
        ROBOT_TRACKING=TRACKING_STOP;
	      ROBOT_PUT=PUT_STOP;
	      ROBOT_TURNAROUND=TURNAROUND_STOP;
	      ROBOT_VISION=VISION_STOP;
				
				ROBOT_CALIBRATION=CALIBRATION_WALL;
				if(ROBOT_CALIBRATION==CALIBRATION_SUCCEEDED)
			  {
			    STATE_COUNT.CALIBRATION_count=2;//设为2，跳出第一次校准模式，进入正常校准触发模式
					VISION_SEND_CONTROL=VISION_ASK_JUDGEMENT_MODE;//向树莓派发送识别请求
					ROBOT_CALIBRATION=CALIBRATION_STOP;
				  ROBOT_STATE=START_TO_MIDDLE;
			  }
			}
			else if(ROBOT_CALIBRATION==CALIBRATION_WALL||ROBOT_CALIBRATION==CALIBRATION_BLACK)//通过类似中断的操作触发(顶墙或黑线校准)
      {
				ROBOT_GRAB=GRAB_STOP;
        ROBOT_TRACKING=TRACKING_STOP;
	      ROBOT_PUT=PUT_STOP;
	      ROBOT_TURNAROUND=TURNAROUND_STOP;
	      ROBOT_VISION=VISION_STOP;
				if(ROBOT_CALIBRATION==CALIBRATION_SUCCEEDED)
				{
					ROBOT_CALIBRATION=CALIBRATION_STOP;
					ROBOT_STATE=LAST_STATE;//回到路径跟踪里面
				}
			}
			else if(ROBOT_CALIBRATION==CALIBRATION_PATHOVER)//路径终点校准中断触发
      {
				ROBOT_GRAB=GRAB_STOP;
        ROBOT_TRACKING=TRACKING_STOP;
	      ROBOT_PUT=PUT_STOP;
	      ROBOT_TURNAROUND=TURNAROUND_STOP;  
	      ROBOT_VISION=VISION_STOP;
				if(ROBOT_CALIBRATION==CALIBRATION_SUCCEEDED)
        {
					ROBOT_CALIBRATION=CALIBRATION_STOP;
					ROBOT_STATE=LAST_STATE;
					ROBOT_TRACKING=TRACKING_SUCCEEDED;
				}
			}
		}
		break;
		//转身模式(自编中断触发)
		case TURNAROUND:
		{
			if(ROBOT_TURNAROUND!=TURNAROUND_IT)//直接触发
			{	
			  ROBOT_GRAB=GRAB_STOP;
        ROBOT_TRACKING=TRACKING_STOP;
	      ROBOT_PUT=PUT_STOP;
	      ROBOT_VISION=VISION_STOP;
			  ROBOT_CALIBRATION=CALIBRATION_STOP;
			
			  ROBOT_TURNAROUND=TURNAROUND_STAYBACK;
				if(ROBOT_TURNAROUND==TURNAROUND_SUCCEEDED)//二层中断返回
        {
					ROBOT_TURNAROUND=TURNAROUND_STOP;
					ROBOT_STATE=BEFORE_STATE;
				}
			}
			else if(ROBOT_TURNAROUND==TURNAROUND_IT)//中断触发
      {
			  ROBOT_GRAB=GRAB_STOP;
        ROBOT_TRACKING=TRACKING_STOP;
	      ROBOT_PUT=PUT_STOP;
	      ROBOT_TURNAROUND=TURNAROUND_STOP;
	      ROBOT_VISION=VISION_STOP;
			  ROBOT_CALIBRATION=CALIBRATION_STOP;
				
				if(ROBOT_TURNAROUND==TURNAROUND_SUCCEEDED)
        {
					ROBOT_TURNAROUND=TURNAROUND_STOP;
					ROBOT_STATE=LAST_STATE;
				}
			}
		}
		//开始到中间
		case START_TO_MIDDLE:
		{
		  ROBOT_GRAB=GRAB_STOP;
	    ROBOT_PUT=PUT_STOP;
	    ROBOT_TURNAROUND=TURNAROUND_STOP;
	    ROBOT_CALIBRATION=CALIBRATION_STOP;
			
			ROBOT_VISION=VISION_START;
			ROBOT_TRACKING=TRACKING_START;
			if(ROBOT_TRACKING==TRACKING_SUCCEEDED)
			{		
				ROBOT_VISION=VISION_STOP;//停止视觉数据获取
				calculate_grab_and_put_order();//计算抓取和摆放顺序
				ROBOT_TRACKING=TRACKING_STOP;
				ROBOT_STATE=MIDDLE_TO_TABLE;
			}
		}
		break;
		case MIDDLE_TO_TABLE://中间到物料台
		{
			ROBOT_GRAB=GRAB_STOP;
	    ROBOT_PUT=PUT_STOP;
	    ROBOT_TURNAROUND=TURNAROUND_STOP;
	    ROBOT_VISION=VISION_STOP;
	    ROBOT_CALIBRATION=CALIBRATION_STOP;
			
			ROBOT_TRACKING=TRACKING_START;
			if(ROBOT_TRACKING==TRACKING_SUCCEEDED)
      {
				ROBOT_TRACKING=TRACKING_STOP;
				ROBOT_STATE=GRAB;
			}
		}
		break;
		case GRAB://抓取
		{
	    ROBOT_PUT=PUT_STOP;
	    ROBOT_TURNAROUND=TURNAROUND_STOP;
	    ROBOT_VISION=VISION_STOP;
	    ROBOT_CALIBRATION=CALIBRATION_STOP;
			ROBOT_TRACKING=TRACKING_STOP;
			
			ROBOT_GRAB=GRAB_START;
			if(ROBOT_GRAB==GRAB_SUCCEEDED)
      {
				ROBOT_STATE=TURNAROUND;//后退转身
				ROBOT_GRAB=GRAB_STOP;
				BEFORE_STATE=TURNAROUND_TO_PUT;//转身后状态切换成TURNAROUND_TO_PUT
			}
		}
		break;
		case TURNAROUND_TO_PUT://转身后去往投放区
		{
			ROBOT_PUT=PUT_STOP;
			ROBOT_GRAB=GRAB_STOP;
	    ROBOT_TURNAROUND=TURNAROUND_STOP;
	    ROBOT_VISION=VISION_STOP;
	    ROBOT_CALIBRATION=CALIBRATION_STOP;
			
			ROBOT_TRACKING=TRACKING_START;
			if(ROBOT_TRACKING==TRACKING_SUCCEEDED)
      {
				ROBOT_TRACKING=TRACKING_STOP;
				ROBOT_STATE=PUT;
				STATE_COUNT.TURNAROUND_TO_PUT_count++;
				if(STATE_COUNT.TURNAROUND_TO_PUT_count==3)//抓取投放工作完成
        {
					ROBOT_TRACKING=TRACKING_STOP;
					ROBOT_STATE=OVER_TO_START;
					
				}
			}
	  }
		break;
		case PUT://放置
		{
			ROBOT_GRAB=GRAB_STOP;
	    ROBOT_TURNAROUND=TURNAROUND_STOP;
	    ROBOT_VISION=VISION_STOP;
	    ROBOT_CALIBRATION=CALIBRATION_STOP;
			ROBOT_TRACKING=TRACKING_STOP;
			
			ROBOT_PUT=PUT_START;			
			if(ROBOT_PUT==PUT_SUCCEEDED)
      {
				ROBOT_PUT=PUT_STOP;
				ROBOT_STATE=TURNAROUND;//转身
				BEFORE_STATE=TURNAROUND_TO_TABLE;//转身完了之后切换TURNAROUND_TO_TABLE
				
			}
		}
		break;
		case TURNAROUND_TO_TABLE://转身后回到物料台
		{
			ROBOT_GRAB=GRAB_STOP;
	    ROBOT_TURNAROUND=TURNAROUND_STOP;
	    ROBOT_VISION=VISION_STOP;
	    ROBOT_CALIBRATION=CALIBRATION_STOP;
			ROBOT_PUT=PUT_STOP;	
			
			ROBOT_TRACKING=TRACKING_START;
			if(ROBOT_TRACKING==TRACKING_SUCCEEDED)
      {
				ROBOT_TRACKING=TRACKING_STOP;
				STATE_COUNT.TURNAROUND_TO_TABLE_count++;
				ROBOT_STATE=GRAB;
			}
		}
		break;
		case OVER_TO_START://结束回到起始区
    {
			ROBOT_GRAB=GRAB_STOP;
	    ROBOT_TURNAROUND=TURNAROUND_STOP;
	    ROBOT_VISION=VISION_STOP;
	    ROBOT_CALIBRATION=CALIBRATION_STOP;
			ROBOT_PUT=PUT_STOP;	
			
			ROBOT_TRACKING=TRACKING_START;
			if(ROBOT_TRACKING==TRACKING_SUCCEEDED)
      {
				ROBOT_TRACKING=TRACKING_STOP;
				ROBOT_STATE=STANDBY;
			}
		}
		break;
	}
}





